### ISSUE TITLE
BoK Annual review - Independent IAM Organizations

### ISSUE THREAD

**Issue by meneer** [IDPros/bok#32]
There are a few issues with this publication:
https://bok.idpro.org/article/id/32/

The article sounds more like an advertorial. Text like: "Our publication,..." and "collaborate in our committees to" causes an inconvenient feeling while reading. Either state that the references are copied from the about pages of the organizations, or rewrite impartially.

The current version of the article is not complete. My suggestion is to add:
- EEMA.org
- IDnext.EU

**Comment by mark-drummond** [comment]
The text for the abstracts from each organization was provided by that organization, and reviewed, perhaps lightly, before being published.

To be honest, and I am the one who put these together, I don't think they belong in the BoK at all. Whatever is in the BoK should be testable content that could show up on a certification test and I don't think it would be appropriate to have certification questions related to specific organizations. IMO this stuff sits somewhere between the BoK and the annotated bibliography.

If we use the CISSP CBK as a model, while it does contain references to specific organizations (e.g., referring to NIST standards), it does not have a "chapter" dedicated to highlighting those entities.

It has been a while since I looked at this but I had reached out to some other orgs in the past but did not get any traction. If we think it is worthwhile I could jump back in, ping them again, and add EEMA.org and IDnext.EU to the list. The process here was pretty simple:

1. I ping the IDPro community on Slack looking for suggestions and for contacts,
2. I ping the contact with an example of what we are looking for,
3. Engage Herding Cats mode chasing down submissions.

**Comment by meneer** [comment]
Moving the topic to the AnBib or an Anbib appendix looks like a feasible
solution. If we add a disclaimer about the non-validated information,
readers can make up their mind.
Collecting and sharing the information is too relevant for practitioners to
just ditch it 😉

Greetings,

André

Op do 29 apr. 2021 21:11 schreef Mark Drummond ***@***.***>:

**Comment by coremania** [comment]
Hey Mark, thanks for pulling these together for Issue 1.  I was invited to participate in the annual review process so here are my thoughts on this:

1] BoK inclusion
Now that we've had a year to let the content settle into our space a bit, I'd agree with the above comments that this collection of info is better suited to live elsewhere, and I'd put in a vote for the Annotated Bibliography.

As the BoK content aligns more closely with examinable material for the certification program, then this material probably deserves to be re-homed.

2] Organizational info
Thanks for reflecting above that the organizations submitted this information about themselves.  At the time, their self-representative comments must have been true!  One year later, the major aim of those organizations is likely sound, at least that is what I gleaned from a tour through some of the linked web sites.

If we're going to re-home the content to the Anno Bib, then I'd assume we apply the refresh process of that resource to make sure that the collected information was still sound.  That being said, I should remind myself of what the refresh process for the Anno Bib is!

**Comment by dmark** [comment]
It is agreed that we will move the "organizations" content into the anno biblio. I'll start that process. Per @coremania's point, we should do a review / the refresh process for existing entries, and I'll work on getting contacts for @meneer's suggestions as well.

**Comment by hlflanagan** [comment]
This article has been removed from the BoK.
