### ISSUE TITLE
Refresh of Introduction to IAM Architecture

### ISSUE THREAD

**Issue by hlflanagan** [IDPros/bok#67]
See https://bok.idpro.org/site/article-refresh-process/

https://bok.idpro.org/article/id/38/

**Comment by hlflanagan** [comment]
From Mark Cox: The article is still accurate, relevant, and complete. No change required.

**Comment by paulfigura** [comment]
Hi @hlflanagan !

I did my review, here are the notes:

* RACF was never defined in the article. It is to be an anachronistic IBM product from the 70’s, that protected access rights to mainframes. I would suggest adding that to the glossary. (FYI I had to google it, because I never worked on it in my 15 years in IAM)
* The general coverage of cloud Architecture for IAM is very light, this article takes a heavy “on-prem” approach to t’s definitions.
* The section about IGA,  Identity standards are still perfectly up to date.
* The section for Access Management is correct, but missing nuance about how more modern sidecar patterns may fit in. (again, Cloud stuff)

**_Overall This article is good enough for another year,_** but I believe the next review (2022?) will need an adjustment or major review to address cloud IAM architecture concerns, which will be the most relevant.

**Comment by cameronka** [comment]
@paulfigura thanks i agree there could be some more meat related to IAM Hybrid Cloud Architecture, i'll put together an update.

also agree on RACF, probably could be removed and still keep intended context

@hlflanagan you can task me with the updates!

**Comment by hlflanagan** [comment]
Article was updated - see v2 - https://bok.idpro.org/article/id/38/
